// export {ClientHome } from '../../../pages/client/Home/ClientHome'
export {Hero} from '../client/Hero/Hero'
export {Features} from './Features/Features'
export {AIBasedModel} from '../client/AIBasedModel/AIBasedModel'
export {AIModelBasedSecond} from '../client/AIModelBasedSecond/AIModelBasedSecond'
export {StockDashboard} from '../client/StockDashboard/StockDashboard'
export {StockDetails} from '../client/StockDetail/StockDetails'